// Optional real-browser smoke test. Install Playwright and its Chromium binary
// locally, then run npm run test:browser. Does not change source or examples.
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { createRequire } from 'node:module';
import { spawn } from 'node:child_process';
import { makeEmptyBuilding } from './src/model.js';
const require=createRequire(import.meta.url);
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const browser=await chromium.launch({headless:true});
const screenshots=process.env.SCREENSHOT_DIR||fs.mkdtempSync(path.join(os.tmpdir(),'building-browser-'));
fs.mkdirSync(screenshots,{recursive:true});
const server=spawn(process.execPath,['server.mjs'],{env:{...process.env,PORT:'0'},stdio:['ignore','pipe','pipe']});
try{
  const port=await new Promise((resolve,reject)=>{
    let text='';const timer=setTimeout(()=>reject(new Error('Server startup timed out')),5000);
    server.stdout.on('data',chunk=>{text+=chunk;const match=/localhost:(\d+)/.exec(text);if(match){clearTimeout(timer);resolve(Number(match[1]));}});
    server.on('error',reject);
  });
  const page=await browser.newPage({viewport:{width:1440,height:900},acceptDownloads:true});
  const errors=[];page.on('pageerror',error=>errors.push(error.message));
  await page.goto(`http://localhost:${port}`);
  await page.locator('#example-select').selectOption('examples/barn_v2');
  await page.waitForFunction(()=>document.querySelector('#building-name').value==='Barn_v2');
  assert.equal(await page.locator('#intentional-open-toggle').isChecked(),true);
  assert.equal(await page.locator('.validation-warning, .validation-error').count(),0);
  assert.equal(await page.locator('#review-checks-btn').textContent(),'Checks: clear');
  await page.locator('#review-checks-btn').click();
  assert.equal(await page.evaluate(()=>document.activeElement.id),'validation-summary');
  await page.locator('#grid-size').evaluate(el=>{for(let p=el.parentElement;p;p=p.parentElement)if(p.tagName==='DETAILS')p.open=true;});
  const priorGrid=await page.locator('#grid-size').inputValue();
  await page.locator('#grid-size').fill('1001');await page.locator('#grid-size').press('Tab');
  assert.equal(await page.locator('#grid-size').inputValue(),priorGrid);
  assert.match(await page.locator('#status-text').textContent(),/Setting unchanged/);
  await page.locator('details.advanced-options:has(#floor-wall-height)').evaluate(el=>el.open=true);
  await page.locator('#floor-wall-height').fill('3.6');
  await page.locator('#floor-wall-height').press('Tab');
  await page.locator('#floor-select').selectOption('1');
  assert.match(await page.locator('#floor-level-summary').textContent(),/Base 3.78 m/);
  assert.equal(await page.locator('#floor-elevation').inputValue(),'');
  await page.locator('#floor-elevation').fill('-10');
  await page.locator('#floor-elevation').press('Tab');
  assert.equal(await page.locator('#floor-elevation').inputValue(),'','invalid level change must roll back');
  await page.locator('#undo-btn').click();
  assert.equal(await page.locator('#floor-wall-height').inputValue(),'');
  await page.locator('#example-select').selectOption('examples/variable_levels');
  await page.waitForFunction(()=>document.querySelector('#building-name').value==='Variable story heights');
  await page.locator('#floor-select').selectOption('2');
  await page.locator('#delete-floor-btn').click();
  assert.equal(await page.locator('#floor-select option').count(),2);
  await page.locator('#undo-btn').click();
  assert.equal(await page.locator('#floor-select option').count(),3);
  await page.locator('#export-profile').selectOption('generic');
  const downloading=page.waitForEvent('download');await page.locator('#export-btn').click();
  const download=await downloading;assert.equal(await download.failure(),null);
  await page.locator('#new-btn').click();
  await page.locator('[data-tool="wall"]').click();
  const box=await page.locator('#plan-canvas').boundingBox();
  for(const [x,y] of [[120,120],[360,120],[360,360],[120,360],[122,122]])await page.mouse.click(box.x+x,box.y+y);
  assert.match(await page.locator('#status-text').textContent(),/loop closed/);
  assert.equal(await page.getByLabel('Full story height').count(),1);
  await page.locator('[data-tool="region"]').click();
  await page.mouse.move(box.x+170,box.y+170);await page.mouse.down();
  await page.mouse.move(box.x+300,box.y+300,{steps:5});await page.mouse.up();
  await page.getByLabel('Region name',{exact:true}).fill('Workshop A');
  await page.getByLabel('Region name',{exact:true}).press('Tab');
  assert.equal(await page.locator('#region-list button').count(),1);
  assert.match(await page.locator('#region-list').textContent(),/Workshop A/);
  await page.locator('#region-list button').click();
  await page.getByRole('button',{name:'Delete selection',exact:true}).click();
  assert.equal(await page.locator('#region-list button').count(),0);
  await page.locator('#undo-btn').click();
  assert.equal(await page.locator('#region-list button').count(),1);
  await page.locator('#example-select').selectOption('examples/editable_junctions');
  await page.waitForFunction(()=>document.querySelector('#building-name').value==='Editable wall junctions');
  const editBox=await page.locator('#plan-canvas').boundingBox();
  const editScale=Math.max(18,Math.min(90,Math.min(editBox.width/12,editBox.height/12)));
  const at=(x,z)=>({x:editBox.x+editBox.width/2+x*editScale,y:editBox.y+editBox.height/2+z*editScale});
  let pt=at(-1,0);await page.mouse.click(pt.x,pt.y);
  assert.equal(await page.getByLabel('Move connected endpoints').isChecked(),true);
  pt=at(1,0);await page.mouse.move(pt.x,pt.y);await page.mouse.down();
  pt=at(1.5,.5);await page.mouse.move(pt.x,pt.y,{steps:8});await page.mouse.up();
  assert.equal(Number(await page.getByLabel('End X',{exact:true}).inputValue()),1.5);
  assert.equal(Number(await page.getByLabel('End Z',{exact:true}).inputValue()),.5);
  assert.match(await page.locator('#status-text').textContent(),/Moved 3 wall/);
  await page.locator('#undo-btn').click();
  pt=at(-1,0);await page.mouse.click(pt.x,pt.y);
  assert.equal(Number(await page.getByLabel('End X',{exact:true}).inputValue()),1);
  assert.equal(Number(await page.getByLabel('End Z',{exact:true}).inputValue()),0);
  await page.locator('#example-select').selectOption('examples/courtyard_regions');
  await page.waitForFunction(()=>document.querySelector('#building-name').value==='Courtyard regions');
  // Group-move browser regression. Kept separate from the Node DOM adapter.
  const group=makeEmptyBuilding();group.name='Group move browser';
  group.floors[0].walls=[['north',-4,-3,4,-3],['east',4,-3,4,3],['south',4,3,-4,3],['west',-4,3,-4,-3]].map(([id,ax,az,bx,bz])=>({id,role:'exterior',a:{x:ax,z:az},b:{x:bx,z:bz},height:null}));
  group.floors[0].openings=[{id:'door',type:'door',doorStyle:'empty',wallId:'south',t:.5,width:1,height:2.1}];
  await page.locator('#load-json-input').setInputFiles({name:'group.building.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(group))});
  await page.waitForFunction(()=>document.querySelector('#building-name').value==='Group move browser');
  await page.locator('[data-view="plan"]').click();
  await page.locator('#selection-filter').selectOption('wall');
  const gb=await page.locator('#plan-canvas').boundingBox(),gs=Math.max(18,Math.min(90,Math.min(gb.width/10,gb.height/8)));
  const gp=(x,z)=>({x:gb.x+gb.width/2+x*gs,y:gb.y+gb.height/2+z*gs});
  const mouseClick=async(x,z)=>{const p=gp(x,z);await page.mouse.click(p.x,p.y);};
  await mouseClick(0,-3);await page.keyboard.down('Shift');await mouseClick(4,0);await page.keyboard.up('Shift');
  assert.equal(await page.locator('#group-count').textContent(),'2 selected');
  await page.locator('#clear-selection-btn').click();
  let p=gp(-4.5,-3.5);await page.mouse.move(p.x,p.y);await page.mouse.down();p=gp(4.5,3.5);await page.mouse.move(p.x,p.y,{steps:6});await page.mouse.up();
  assert.equal(await page.locator('#group-count').textContent(),'4 selected');
  p=gp(0,-3);await page.mouse.move(p.x,p.y);await page.mouse.down();p=gp(1,-2);await page.mouse.move(p.x,p.y,{steps:6});
  await page.screenshot({path:path.join(screenshots,'group_drag.png'),fullPage:true});
  await page.mouse.up();
  const savedBlueprint=async()=>{
    await page.locator('.file-menu').evaluate(el=>el.open=true);
    const pending=page.waitForEvent('download');await page.locator('#save-json-btn').click();const file=await pending;
    assert.equal(await file.failure(),null);return JSON.parse(fs.readFileSync(await file.path(),'utf8'));
  };
  const shifted=await savedBlueprint();assert.deepEqual(shifted.floors[0].walls[0].a,{x:-3,z:-2});assert.equal(shifted.floors[0].openings[0].t,.5);
  await page.locator('#undo-btn').click();assert.deepEqual((await savedBlueprint()).floors[0].walls[0].a,{x:-4,z:-3});
  await page.locator('#select-all-btn').click();await page.locator('#move-selection-btn').click();
  p=gp(0,0);await page.mouse.move(p.x,p.y);await page.mouse.down();p=gp(1,1);await page.mouse.move(p.x,p.y,{steps:4});await page.keyboard.press('Escape');await page.mouse.up();
  assert.deepEqual((await savedBlueprint()).floors[0].walls[0].a,{x:-4,z:-3});
  await page.locator('#selection-filter').selectOption('all');
  await page.locator('#example-select').selectOption('examples/basement_markers');
  await page.waitForFunction(()=>document.querySelector('#building-name').value==='Basement and named markers');
  await page.locator('#add-floor-below-btn').click();assert.equal(await page.locator('#floor-select option').count(),3);
  await page.locator('#floor-select').selectOption('2');assert.match(await page.locator('#floor-level-summary').textContent(),/Base 0.00 m/);
  await page.locator('#undo-btn').click();await page.locator('#floor-select').selectOption('0');await page.locator('#move-floor-up-btn').click();assert.match(await page.locator('#status-text').textContent(),/stair connection/);
  await page.locator('#floor-remove-stairs').check();await page.locator('#move-floor-up-btn').click();assert.equal(await page.locator('#floor-label').inputValue(),'Basement');
  await page.locator('#marker-list button').click();await page.getByLabel('Marker name',{exact:true}).fill('Utility reference');await page.getByLabel('Marker name',{exact:true}).press('Tab');
  await page.getByLabel('Notes (JSON only)',{exact:true}).fill('Browser marker note');await page.getByLabel('Notes (JSON only)',{exact:true}).press('Tab');
  const withNotes=await savedBlueprint();assert.equal(withNotes.floors[1].markers[0].details,'Browser marker note');assert.equal(withNotes.floors[1].stairs.length,0);
  await page.screenshot({path:path.join(screenshots,'floor_marker_controls.png'),fullPage:true});
  const picking=makeEmptyBuilding();picking.name='Picking check';picking.roof.type='none';
  picking.roofSections=['A','B'].map(id=>({id:'roof-'+id,label:'Canopy '+id,minX:-3,maxX:3,minZ:-3,maxZ:3,type:'flat',direction:'x',baseY:2.8,pitch:35,overhang:0,gableEnds:'none'}));
  await page.locator('#load-json-input').setInputFiles({name:'picking.building.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(picking))});
  await page.waitForFunction(()=>document.querySelector('#building-name').value==='Picking check');
  for(const [width,height] of [[1440,900],[768,1024],[390,844]]){
    await page.setViewportSize({width,height});
    await page.locator('[data-view="plan"]').click();
    // Element click scrolls the canvas into view first (at 390 px it sits below the fold).
    await page.locator('#plan-canvas').click();
    assert.equal(await page.locator('#selection-candidates button').count(),2);
    await page.getByRole('button',{name:'Roof section · Canopy B @ 2.80 m',exact:true}).click();
    assert.equal(await page.locator('#selection-candidates button[aria-pressed="true"]').textContent(),'Roof section · Canopy B @ 2.80 m');
    assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1),'selection chooser must fit width');
    await page.screenshot({path:path.join(screenshots,`selection_${width}.png`),fullPage:true});
    await page.locator('[data-view="preview"]').click();
    assert.equal(await page.locator('#export-profile').isVisible(),true,'export controls must remain accessible');
    assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1),'page must fit width');
    await page.screenshot({path:path.join(screenshots,`editor_${width}.png`),fullPage:true});
  }
  assert.deepEqual(errors,[]);
  await page.locator('#example-select').selectOption('examples/roof_attachment');
  await page.waitForFunction(()=>document.querySelector('#building-name').value==='Explicit roof attachment');
  await page.locator('[data-view="preview"]').click();
  await page.locator('#preview-mode').selectOption('roofs');
  await page.locator('#preview-overlay').selectOption('attachments');
  await page.locator('#preview-roof').selectOption('roofSections_8');
  await page.locator('#preview-details').evaluate(el=>el.open=true);
  assert.match(await page.locator('#preview-notes').textContent(),/Attached canopy → Main host roof/);
  for(const [width,height] of [[1440,900],[768,1024],[390,844]]){
    await page.setViewportSize({width,height});
    await page.locator('#preview-frame').click();
    assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1),'preview controls must fit width');
    const stage=await page.locator('#preview-canvas').boundingBox();assert.ok(stage.height>=120);
    await page.screenshot({path:path.join(screenshots,`roof_guides_${width}.png`),fullPage:true});
  }
  await page.locator('#example-select').selectOption('examples/twostory');
  await page.waitForFunction(()=>document.querySelector('#preview-roof').value==='');
  await page.locator('#preview-mode').selectOption('floor');
  await page.locator('#preview-overlay').selectOption('footprint');
  await page.locator('#preview-floor').selectOption('1');
  assert.equal(await page.locator('#floor-select').inputValue(),'1');
  assert.match(await page.locator('#preview-status').textContent(),/Floor 2:.*before stair\/platform cutouts/);
  await page.locator('#preview-overlay').selectOption('none');
  assert.equal(await page.locator('#preview-guide-scope').isVisible(),false);
  assert.deepEqual(errors,[]);
  const checkDownloading=page.waitForEvent('download');
  await page.locator('#download-check-report-btn').click();
  const checkDownload=await checkDownloading;assert.equal(await checkDownload.failure(),null);
  assert.match(checkDownload.suggestedFilename(),/\.checks\.json$/);
  const checkReport=JSON.parse(fs.readFileSync(await checkDownload.path(),'utf8'));
  assert.equal(checkReport.kind,'building-check-report');assert.equal(checkReport.verification.godot,'not-run');
  await page.locator('#example-select').selectOption('farmhouse_example');
  await page.locator('.validation-actions button').filter({hasText:'Show stair'}).click();
  assert.equal(await page.locator('#floor-select').inputValue(),'0');
  assert.equal(await page.evaluate(()=>document.activeElement.id),'selection-form');
  assert.equal(await page.locator('#plan-view').evaluate(el=>el.classList.contains('active')),true);
  for(const [width,height] of [[1440,900],[768,1024],[390,844]]){
    await page.setViewportSize({width,height});await page.locator('#review-checks-btn').click();
    assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1),'diagnostic actions must fit width');
    await page.screenshot({path:path.join(screenshots,`diagnostic_actions_${width}.png`),fullPage:true});
  }
  assert.deepEqual(errors,[]);
  console.log('PASS browser load, examples, level edits, invalid rollback, diagnostic navigation, undo, deletion, ZIP export and responsive layout');
  console.log('Screenshots: '+screenshots);
}finally{server.kill();await browser.close();}
