// One suite registry for the CLI and infrastructure/release gates.
export const core=['castle-review-tests.mjs','reachability-tests.mjs','render-tests.mjs','import-cleanup-tests.mjs','check-report-tests.mjs','diagnostic-navigation-tests.mjs','workflow-tests.mjs','validation-feedback-tests.mjs','opening-shape-tests.mjs','angled-junction-tests.mjs','profile-junction-tests.mjs','concave-roof-tests.mjs','profile-roof-tests.mjs','wall-profile-tests.mjs','region-tests.mjs','polygon-tests.mjs','tests.mjs','regression-tests.mjs','authoring-tests.mjs','editor-tests.mjs','wall-edit-tests.mjs','roof-tests.mjs','selection-tests.mjs','group-edit-tests.mjs','floor-marker-tests.mjs','junction-footprint-tests.mjs','cli-tests.mjs','asset-tests.mjs','transaction-tests.mjs','building-transaction-tests.mjs','opening-placement-tests.mjs','floor-transaction-tests.mjs','floor-lifecycle-tests.mjs','stair-transaction-tests.mjs','stair-lifecycle-tests.mjs','platform-transaction-tests.mjs','platform-lifecycle-tests.mjs','preview-review-tests.mjs','overlay-tests.mjs','web-preview-tests.mjs','attachment-diagnostics-tests.mjs','release-check-tests.mjs'];
export const suites={core,
  geometry:['castle-review-tests.mjs','opening-shape-tests.mjs','angled-junction-tests.mjs','profile-junction-tests.mjs','concave-roof-tests.mjs','profile-roof-tests.mjs','wall-profile-tests.mjs','polygon-tests.mjs','tests.mjs','regression-tests.mjs','roof-tests.mjs','junction-footprint-tests.mjs','attachment-diagnostics-tests.mjs'],
  editor:['import-cleanup-tests.mjs','check-report-tests.mjs','diagnostic-navigation-tests.mjs','validation-feedback-tests.mjs','opening-shape-tests.mjs','wall-profile-tests.mjs','region-tests.mjs','editor-tests.mjs','wall-edit-tests.mjs','selection-tests.mjs','group-edit-tests.mjs','floor-marker-tests.mjs','web-preview-tests.mjs'],
  cli:['cli-tests.mjs','reachability-tests.mjs','render-tests.mjs','check-report-tests.mjs','import-cleanup-tests.mjs'],transactions:['workflow-tests.mjs','transaction-tests.mjs','building-transaction-tests.mjs','opening-placement-tests.mjs','floor-transaction-tests.mjs','floor-lifecycle-tests.mjs','stair-transaction-tests.mjs','stair-lifecycle-tests.mjs','platform-transaction-tests.mjs','platform-lifecycle-tests.mjs'],release:['release-check-tests.mjs'],
  preview:['preview-review-tests.mjs','overlay-tests.mjs','web-preview-tests.mjs'],
  'preview-render':['preview-render-tests.mjs','web-preview-render-tests.mjs'],
  assets:['asset-tests.mjs'],'engine-assets':['workflow-engine-tests.mjs','render-engine-tests.mjs','opening-shape-engine-tests.mjs','profile-roof-engine-tests.mjs','wall-profile-engine-tests.mjs','region-engine-tests.mjs','polygon-engine-tests.mjs','asset-engine-tests.mjs','stair-engine-tests.mjs','stair-lifecycle-engine-tests.mjs','platform-engine-tests.mjs','platform-lifecycle-engine-tests.mjs','floor-marker-engine-tests.mjs','floor-lifecycle-engine-tests.mjs'],infrastructure:['infrastructure-tests.mjs']};
